/* Seed data for events, downloads and gallery collections */

export const SEED_GALLERIES = [
  { id: 'quivers-arrows-2023', name: "Quiver's Arrows 2023", description: 'The inaugural edition — a prophetic call to the next generation.' },
  { id: 'quivers-awakening-2024', name: "Quiver's Awakening 2024", description: 'Northern Edition (February 2024) — expanding the reach across the nation.' },
  { id: 'quivers-forge-2024', name: "Quiver's Forge 2024", description: 'A furnace of refining — shaping vessels for honour.' },
  { id: 'quivers-immersion-2025', name: "Quiver's Immersion 2025", description: 'Diving deep into the presence and purpose of God.' },
];


export const SEED_EVENTS = [
  {
    title: "Quiver's Conference 2023",
    theme: 'Arrows',
    status: 'past',
    date: '2023-04-15',
    description: 'Main Edition',
    location: 'Nigeria',
    time: '10:00 AM',
    image_url: '',
    registration_enabled: false,
    form_fields: '[]',
  },
  {
    title: "Quiver's Conference 2024 (Northern)",
    theme: 'Awakening',
    status: 'past',
    date: '2024-02-10',
    description: 'Northern Edition',
    location: 'Kano, Nigeria',
    time: '10:00 AM',
    image_url: '',
    registration_enabled: false,
    form_fields: '[]',
  },
  {
    title: "Quiver's Conference 2024",
    theme: 'Forge',
    status: 'past',
    date: '2024-04-20',
    description: 'Annual Conference',
    location: 'Ibadan, Nigeria',
    time: '9:00 AM',
    image_url: '',
    registration_enabled: false,
    form_fields: '[]',
  },
  {
    title: "Quiver's Conference 2025",
    theme: 'Immersion',
    status: 'past',
    date: '2025-04-12',
    description: 'Annual Conference',
    location: 'Nigeria',
    time: '9:00 AM',
    image_url: '',
    registration_enabled: false,
    form_fields: '[]',
  },
  {
    title: "Quiver's Conference 2026",
    theme: 'Envoys of Light',
    status: 'upcoming',
    date: '2026-04-18',
    description: 'International Quivers Conference 2026 continues a legacy of encounters that have shaped lives, ignited faith, and released voices across generations.',
    location: 'To Be Announced',
    time: 'TBA',
    image_url: '',
    registration_enabled: true,
    form_fields: JSON.stringify([
      { id: 'first_name', label: 'First Name', type: 'text', required: true, placeholder: 'First name' },
      { id: 'last_name', label: 'Last Name', type: 'text', required: true, placeholder: 'Last name' },
      { id: 'email', label: 'Email Address', type: 'email', required: true, placeholder: 'your@email.com' },
      { id: 'phone', label: 'Phone Number', type: 'tel', required: false, placeholder: '+234 000 000 0000' },
      { id: 'location', label: 'State / City', type: 'text', required: false, placeholder: 'Where are you joining from?' },
      { id: 'note', label: 'Prayer Request or Note', type: 'textarea', required: false, placeholder: "Anything you'd like us to pray about or know..." },
    ]),
  },
  {
    title: 'First Saturday Service',
    theme: '',
    status: 'recurring',
    date: '2026-01-01',
    description: 'Monthly Gathering',
    location: 'Nigeria',
    time: 'Every 1st Saturday · 10:00 AM',
    image_url: '',
    registration_enabled: true,
    form_fields: JSON.stringify([
      { id: 'first_name', label: 'First Name', type: 'text', required: true, placeholder: 'First name' },
      { id: 'last_name', label: 'Last Name', type: 'text', required: true, placeholder: 'Last name' },
      { id: 'email', label: 'Email Address', type: 'email', required: true, placeholder: 'your@email.com' },
      { id: 'phone', label: 'Phone Number', type: 'tel', required: false, placeholder: '+234 000 000 0000' },
    ]),
  },
  {
    title: 'Mid-Week Gathering',
    status: 'recurring',
    date: '2026-01-01',
    description: 'Prayer & Fellowship',
    location: 'Nigeria',
    time: 'Every Wednesday · Details TBA',
    image_url: '',
    registration_enabled: false,
    form_fields: '[]',
  },
];

export const SEED_DOWNLOADS = [
  {
    title: 'Walking in Your Kingdom Identity',
    url: '#',
    description: "Jesse Falodun — Quiver's Immersion 2025",
    category: 'Sermon',
    type: 'audio',
  },
  {
    title: 'Arise: Walking Into Your Appointed Season',
    url: '#',
    description: "Jesse Falodun — Quiver's Forge 2024",
    category: 'Teaching',
    type: 'video',
  },
  {
    title: 'The Sound That Changes Atmospheres',
    url: '#',
    description: "Guest Minister — Quiver's Arrows 2023",
    category: 'Sermon',
    type: 'audio',
  },
  {
    title: 'Positioned for Overflow',
    url: '#',
    description: 'Guest Minister — Awakening 2023',
    category: 'Sermon',
    type: 'audio',
  },
  {
    title: 'Forge Conference Notes 2024',
    url: '#',
    description: "Quiver's Conference Programme Manual",
    category: 'Manual',
    type: 'pdf',
  },
  {
    title: 'He Who Calls Is Faithful',
    url: '#',
    description: 'Jesse Falodun — Weekly Teaching',
    category: 'Teaching',
    type: 'video',
  },
];
